### Excercise - 1: MDP Tool Box

In [ ]:
!pip install pymdptoolbox

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for pymdptoolbox: filename=pymdptoolbox-4.0b3-py3-none-any.whl size=25655 sha256=48a3a57afda2b1f24872108079875a866461a5e694b8c4fa4be29dd6358a5f9f
  Stored in directory: /root/.cache/pip/wheels/85/c2/e4/29e0b5aab8da79e0f54cf086f8549d47c824e5242ae687e93a
Successfully built pymdptoolbox


**mdptoolbox.mdp.FiniteHorizon(transition,reward,discount,N,h=none,skip_check=False)**

In [ ]:
import mdptoolbox

In [ ]:
import mdptoolbox.example

In [ ]:
P,R=mdptoolbox.example.forest()

In [ ]:
fh=mdptoolbox.mdp.FiniteHorizon(P,R,0.9,3)

In [ ]:
fh.run()

In [ ]:
fh.V

array([[2.6973, 0.81  , 0.    , 0.    ],
       [5.9373, 3.24  , 1.    , 0.    ],
       [9.9373, 7.24  , 4.    , 0.    ]])

In [ ]:
fh.policy

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

**mdptoolbox.example.forest(S=3,r1=4,r2=2,p=0.1,is_sparse=False)**

In [ ]:
import mdptoolbox.example
P,R=mdptoolbox.example.forest()

In [ ]:
P

array([[[0.1, 0.9, 0. ],
        [0.1, 0. , 0.9],
        [0.1, 0. , 0.9]],

       [[1. , 0. , 0. ],
        [1. , 0. , 0. ],
        [1. , 0. , 0. ]]])

In [ ]:
R

array([[0., 0.],
       [0., 1.],
       [4., 2.]])

In [ ]:
Psp,Rsp=mdptoolbox.example.forest(is_sparse=True)
len(Psp)

2

In [ ]:
Psp[0]

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [ ]:
Psp[1]

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [ ]:
Rsp

array([[0., 0.],
       [0., 1.],
       [4., 2.]])

In [ ]:
(Psp[0].todense()==P[0]).all()

True

In [ ]:
(Rsp==R).all()

True

**mdptoolbox.example.rand(S,A,is_sparse=False,mask=None)**

In [ ]:
import numpy,mdptoolbox.example

In [ ]:
numpy.random.seed(0)

In [ ]:
P,R=mdptoolbox.example.rand(4,3)

In [ ]:
P

array([[[0.21977283, 0.14889403, 0.30343592, 0.32789723],
        [1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.43718772, 0.54480359, 0.01800869],
        [0.39766289, 0.39997167, 0.12547318, 0.07689227]],

       [[1.        , 0.        , 0.        , 0.        ],
        [0.32261337, 0.15483812, 0.32271303, 0.19983549],
        [0.33816885, 0.2766999 , 0.12960299, 0.25552826],
        [0.41299411, 0.        , 0.58369957, 0.00330633]],

       [[0.32343037, 0.15178596, 0.28733094, 0.23745272],
        [0.36348538, 0.24483321, 0.16114188, 0.23053953],
        [1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        , 0.        ]]])

In [ ]:
R

array([[[-0.23311696,  0.58345008,  0.05778984,  0.13608912],
        [-0.07704128,  0.        , -0.        ,  0.        ],
        [ 0.        ,  0.22419145,  0.23386799,  0.88749616],
        [-0.3691433 , -0.27257846,  0.14039354, -0.12279697]],

       [[-0.77924972,  0.        , -0.        , -0.        ],
        [ 0.47852716, -0.92162442, -0.43438607, -0.75960688],
        [-0.81211898,  0.15189299,  0.8585924 , -0.3628621 ],
        [ 0.35563307, -0.        ,  0.47038804,  0.92437709]],

       [[-0.4051261 ,  0.62759564, -0.20698852,  0.76220639],
        [-0.9616136 , -0.39685037,  0.32034707, -0.41984479],
        [-0.13716313,  0.        , -0.        , -0.        ],
        [ 0.        , -0.        ,  0.55810204,  0.        ]]])

In [ ]:
numpy.random.seed(0)

In [ ]:
Psp,Rsp=mdptoolbox.example.rand(100,5,is_sparse=True)
len(Psp),len(Rsp)

(5, 5)

In [ ]:
Psp[0]

<100x100 sparse matrix of type '<class 'numpy.float64'>'
	with 3363 stored elements in Compressed Sparse Row format>

In [ ]:
Rsp[0]

<100x100 sparse matrix of type '<class 'numpy.float64'>'
	with 3363 stored elements in Compressed Sparse Row format>

In [ ]:
Psp[1].nnz==Rsp[1].nnz

True

**mdptoolbox.example.small()**

In [ ]:
P, R = mdptoolbox.example.small()
P

array([[[0.5, 0.5],
        [0.8, 0.2]],

       [[0. , 1. ],
        [0.1, 0.9]]])

In [ ]:
R

array([[ 5, 10],
       [-1,  2]])